### ISSUE TITLE
crash in open collection item list on empty collection

### ISSUE THREAD

**Issue by alja** [alja/Fireworks2#20]
FW2EveManager FillImpliedSelected

Thread 1 "fire" received signal SIGSEGV, Segmentation fault.
ROOT::Experimental::REveDataCollection::GetDataPtr (this=0xc7f4050, i=0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/inc/ROOT/REveDataCollection.hxx:142
142        void *GetDataPtr(Int_t i) const { return  fItemList->fItems[i]->GetDataPtr(); }
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y

**Comment by alja** [comment]
Thread 1 "fire" received signal SIGSEGV, Segmentation fault.
ROOT::Experimental::REveDataCollection::GetDataPtr (this=0xd27e4b0, i=0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/inc/ROOT/REveDataCollection.hxx:142
142        void *GetDataPtr(Int_t i) const { return  fItemList->fItems[i]->GetDataPtr(); }
(gdb) bt
#0  ROOT::Experimental::REveDataCollection::GetDataPtr (this=0xd27e4b0, i=0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/inc/ROOT/REveDataCollection.hxx:142
#1  0x00007ffff7c42265 in ROOT::Experimental::REveDataItemList::GetHighlightTooltip[abi:cxx11](std::set<int, std::less<int>, std::allocator<int> > const&) const (this=0xc3dec30, secondary_idcs=...) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/src/REveDataCollection.cxx:152
#2  0x00007ffff7cba9c0 in ROOT::Experimental::REveSelection::WriteCoreJson (this=0x3d88380, j=...) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/src/REveSelection.cxx:691
#3  0x00007ffff7cb2e82 in ROOT::Experimental::REveScene::StreamRepresentationChanges (this=0x12a94c0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/src/REveScene.cxx:254
#4  0x00007ffff7cb1f04 in ROOT::Experimental::REveScene::ProcessChanges (this=0x12a94c0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/src/REveScene.cxx:111
#5  0x00007ffff7c7cbef in ROOT::Experimental::REveManager::DoRedraw3D (this=0x38cd1f0) at /data2/alja/fwWeb/myROOT/root/graf3d/eve7/src/REveManager.cxx:251

**Comment by alja** [comment]
fixed
